file = FileNameJoin[{DirectoryName[$InputFileName], "dist", "SSGReciprocalDatabase-0.8.0.paclet"}];
Print["Isolated user base: ", $UserBaseDirectory];
installed = PacletInstall[file];
Print[installed];
If[!MatchQ[installed, _PacletObject], Exit[1]];
Get["SSGReciprocalDatabase`"];
Print["Loaded: ", FindFile["SSGReciprocalDatabase`"]];
If[SSGReciprocalDatabaseVersion =!= {0,8,0}, Exit[2]];
If[!StringStartsQ[FindFile["SSGReciprocalDatabase`"], $UserBaseDirectory], Exit[3]];
If[getSSGReciprocalMagneticSpaceGroup["N143.10.1"]["BNSNumber"] =!= "147.15", Exit[4]];
If[getSSGReciprocalMagneticSpaceGroup["N65.9.123"]["BNSNumber"] =!= "37.186", Exit[5]];
If[getSSGReciprocalFamilySpaceGroup["N143.10.1"]["InternationalNumber"] =!= 147, Exit[6]];
If[Head[showSSGReciprocalMagneticGroup["N143.10.1"]] =!= Column, Exit[7]];
If[Head[showSSGReciprocalGenTab["N143.16.1"]] === Missing, Exit[8]];
Print["PASS: isolated PacletInstall, load, magnetic/family queries and tables"];
Exit[0];
